<?php
	$sections['resume'] = array(
		'title'            => 'Resume',
		'type'             => 'timeline',
		'headerBackground' => 'assets/img/01-resume.jpg',
		'icon'             => 'format_quote',
		'content'          => array(
			array(
				'title'       => 'Smart contract / Blockchain Engineer',
				'icon'        => 'bitcoin',
				'color'       => 'danger',
				'date'        => '2021-present',
				'description' =>
'<ul>
	<li>Smart contract / Blockchain engineer at <a href="https://openzeppelin.com/" target="_blank" class="text-%class%">OpenZeppelin</a></li>
</ul>',
			),
			array(
				'title'       => 'Research Engineer',
				'icon'        => 'bitcoin',
				'color'       => 'danger',
				'date'        => '2018-2020',
				'description' =>
'<ul>
	<li>Research engineer at <a href="http://iex.ec/" target="_blank" class="text-%class%">iExec</a></li>
	<li>Recorded talks:
		<ul>
			<li><a href="https://www.youtube.com/watch?v=8w4zRtkfKT0" target="_blank" class="text-%class%">The Magic of Ethereum Addresses (Devcon5)</a></li>
			<li><a href="https://www.youtube.com/watch?v=Cfjyu8oAzh4" target="_blank" class="text-%class%">Upgradeability of self-governed contract (Devcon5)</a></li>
			<li><a href="https://www.youtube.com/watch?v=X5L4fQbUxsA" target="_blank" class="text-%class%">MetaMask MetaTransaction Panel</a></li>
			<li><a href="https://www.youtube.com/watch?v=pLXdo2sUIKM" target="_blank" class="text-%class%">Going Off-Chain: Power Your Application with a Decentralized & Distributed Network (EthDenver 2020)</a></li>
			<li><a href="https://www.youtube.com/watch?v=MYrwnKWfrL0" target="_blank" class="text-%class%">Collateralizing NFTs (NFTNYC 2020)</a></li>
		</ul>
	</li>
	<li>Technical articles on medium:
		<ul>
			<li><a href="https://medium.com/iex-ec/about-trust-and-agents-incentives-4651c138974c"                                                  target="_blank" class="text-%class%">About Trust and Agents Incentives</a></li>
			<li><a href="https://medium.com/iex-ec/poco-series-2-on-the-use-of-staking-to-prevent-attacks-2a5c700558bd"                             target="_blank" class="text-%class%">On the use of staking to prevent attacks</a></li>
			<li><a href="https://medium.com/iex-ec/poco-series-3-poco-protocole-update-a2c8f8f30126"                                                target="_blank" class="text-%class%">Protocol update</a></li>
			<li><a href="https://medium.com/iex-ec/poco-series-4-sgx-enclaves-and-trusted-executions-6f2ebed8d4fa"                                  target="_blank" class="text-%class%">Enclaves and Trusted Executions</a></li>
			<li><a href="https://medium.com/iex-ec/poco-series-5-open-decentralized-brokering-on-the-iexec-platform-67b266e330d8"                   target="_blank" class="text-%class%">Open decentralized brokering on the iExec platform</a></li>
			<li><a href="https://medium.com/iex-ec/poco-series-6-smart-contract-upgradeability-and-governance-68d2cdecd120"                         target="_blank" class="text-%class%">Smart Contract Upgradeability and Governance</a></li>
			<li><a href="https://medium.com/iex-ec/poco-series-7-enslogin-1013e7884ccb"                                                             target="_blank" class="text-%class%">ENSLogin</a></li>
			<li><a href="https://medium.com/iex-ec/poco-series-8-future-proofing-iexec-smart-contract-interoperability-and-modularity-37a3d3613f11" target="_blank" class="text-%class%">Future-proofing iExec - Smart Contract Interoperability and Modularity</a></li>
		</ul>
	</li>
</ul>',
			),
			array(
				'title'       => 'Scientific Consultant',
				'icon'        => 'bitcoin',
				'color'       => 'danger',
				'date'        => '2017-2018',
				'description' => '<ul><li>Algorithm & Blockchain scientific consultant in charge of the design and evaluation of the Proof-of-Contribution algorithms for <a href="http://iex.ec/" target="_blank" class="text-%class%">iExec</a></li></ul>',
			),
			array(
				'title'       => 'PhD Student',
				'icon'        => 'education',
				'color'       => 'info',
				'date'        => '2015-2018',
				'description' => '<ul><li>Topic: "Étude et conception d\'un système de gestion de workflow autonomique pour l\'animation 3D",</li><li><a href="http://avalon.ens-lyon.fr/" target="_blank" class="text-%class%">Avalon</a>, <a href="http://www.ens-lyon.eu/" target="_blank" class="text-%class%">Ecole Normale Supérieure de Lyon</a>, Lyon, France</li><li>Supervised by <a href="http://graal.ens-lyon.fr/~ecaron/" target="_blank" class="text-%class%">Eddy Caron</a></li></ul>',
			),
			array(
				'title'       => 'Research Scholar',
				'icon'        => 'globe',
				'color'       => 'success',
				'date'        => '2014-2015',
				'description' => '<ul><li><a href="http://www.anl.gov/" target="_blank" class="text-%class%">Argonne National Laboratory</a>, Illinois</li></ul>',
			),
			array(
				'title'       => 'Master in Computer Science',
				'icon'        => 'education',
				'color'       => 'info',
				'date'        => '2013-2014',
				'description' => '<ul><li><a href="http://www.univ-lyon1.fr/" target="_blank" class="text-%class%">Université Claude Bernard Lyon 1</a>, Lyon, France.</li><li>Specialization: Image acquisition and processing (Research).</li></ul>',
			),
			array(
				'title'       => 'Research Intern',
				'icon'        => 'globe',
				'color'       => 'success',
				'date'        => 'may-august 2013',
				'description' => '<ul><li><a href="http://http://jfli.cnrs.fr/" target="_blank" class="text-%class%">JFLI</a>, University of Tokyo, Japan</li></ul>',
			),
			array(
				'title'       => 'Master in Computer Science',
				'icon'        => 'education',
				'color'       => 'info',
				'date'        => '2012-2013',
				'description' => '<ul><li><a href="http://www.ens-lyon.fr/DI/" target="_blank" class="text-%class%">Ecole Normale Supérieur de Lyon</a>, Lyon, France.</li></ul>',
			),
			array(
				'title'       => '“Licence” with distinction in Computer Science',
				'icon'        => 'education',
				'color'       => 'info',
				'date'        => '2011-2012',
				'description' => '<ul><li><a href="http://www.ens-lyon.fr/DI/" target="_blank" class="text-%class%">Ecole Normale Supérieur de Lyon</a>, Lyon, France.</li><li>Equivalent to Bachelor</li></ul>',
			),
			array(
				'title'       => 'Honourable Mention in the French national selection for IPhO',
				'icon'        => 'star',
				'color'       => 'warning',
				'date'        => 'april 2010',
				'description' => '<ul><li> International Physics Olympiads.</li></ul>',
			),
			array(
				'title'       => '“Classes préparatoires” in Science',
				'icon'        => 'education',
				'color'       => 'info',
				'date'        => '2009-2011',
				'description' => '<ul><li>Lycée St-Louis, Paris, France.</li><li>Specialization: Computer Science.</li></ul>',
			),
			array(
				'title'       => 'Scientific high school diploma with distinction',
				'icon'        => 'education',
				'color'       => 'info',
				'date'        => 'june 2009',
				'description' => '<ul><li><a href="http://www.lfitokyo.org/" target="_blank" class="text-%class%">Lycée Franco-Japonais de Tokyo - LFJT</a>, Tokyo, Japan.</li></ul>',
			),
		),
		'footer' => '<div class="btn-group btn-group-justified" role="group"><a class="btn btn-danger btn-raised btn-lg" href="//shared.hadriencroubois.com/CrouboisHadrienEN.pdf" target="_blank">View my full resume (English)</a></div>',
	);
?>
