<?php
	$sections['code'] = array(
		'title'            => 'Code',
		'type'             => 'blocks',
		'settings'         => array('class' => 'info', 'width' => 'col-md-4'),
		'headerBackground' => 'assets/img/02-code.jpg',
		'icon'             => 'polymer',
		'content'          => array(
			array(
				'title'   => 'Scheduler++',
				'content' => '<p>Scheduler++ is a distributed platform simulator for experiment with scheduling tactics and communication models</p>
				              <p>Status: active development</p>
				              <div class="progress"><div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width:60%"></div></div>
				              <ul>
				              	<li>Language: C++17</li>
				              	<li>Licence: to be determined</li>
				              	<li>Sources: not yet available</li>
				              </ul>',
			),
			array(
				'title'   => 'MSE-JPS',
				'content' => '<p>MSE-JPS is a new version of the MSE engine using server side data generation from SQL database. This will allow no-script users to have a backup JavaScript free page while helping update the website content.</p>
				              <p>Status: released & maintained</p>
				              <div class="progress"><div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div></div>
				              <ul>
				              	<li>Language: PHP/SQL/JavaScript/CSS</li>
				              	<li>Licence: GPLv3</li>
				              	<li>Sources: <a href="https://github.com/Amxx/MSE-JPS" target="_blank" class="text-%class%">https://github.com/Amxx/MSE-JPS</a></li>
				              </ul>',
			),
			array(
				'title'   => 'Tess++',
				'content' => '<p>An optimised version of the Tess library, providing tesselation and density estimation solutions for HPC applications.</p>
				              <p>Status: active development</p>
				              <div class="progress"><div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:60%"></div></div>
				              <ul>
				              	<li>Language: C++11</li>
				              	<li>Licence: to be determined</li>
				              	<li>Sources: not yet available</li>
				              </ul>',
			),
			array(
				'title'   => 'MSE',
				'content' => '<p>MSE (Mini Site Engine) is a javascript engine for generating minimalistic website which was developped as a CMS to my own website. It then evolved into MSE-JPS, adding mysql database support, noscript minimal functionnality and a full administration interface.</p>
				              <p>Status: released</p>
				              <div class="progress"><div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div></div>
				              <ul>
				              	<li>Language: JavaScript/CSS</li>
				              	<li>Licence: GPLv3</li>
				              	<li>Sources: <a href="https://github.com/Amxx/MSE" target="_blank" class="text-%class%">https://github.com/Amxx/MSE</a></li>
				              </ul>',
			),
			array(
				'title'   => 'Adimx',
				'content' => '<p>A simple header geometry library for C++11 applications.</p>
				              <p>Status: released</p>
				              <div class="progress"><div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div></div>
				              <ul>
				              	<li>Language: C++11</li>
				              	<li>Licence: GPLv3</li>
				              	<li>Sources: <a href="https://github.com/Amxx/Adimx" target="_blank" class="text-%class%">https://github.com/Amxx/Adimx</a></li>
				              </ul>',
			),
			array(
				'title'   => 'MobileReality',
				'content' => '<p>MobileReality is a framework for augmented reality rendering on mobile platform.</p>
				              <p>Status: released</p>
				              <div class="progress"><div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div></div>
				              <ul>
				              	<li>Language: C++11/GLSL</li>
				              	<li>Licence: CeCILL-B</li>
				              	<li>Sources: <a href="https://github.com/Amxx/MobileReality" target="_blank" class="text-%class%">https://github.com/Amxx/MobileReality</a></li>
				              </ul>',
			),
			array(
				'title'   => 'LibGridRCPDM',
				'content' => '<p>LibGridRCPDM is a common implementation of both the Open Grid Forum GridRPC API and GridRPC API Data Management standards. It is completely modular and already supports middleware modules for DIET and Ninf, as well as data manager modules for iRods, OwnCloud, rsync, scp.<p>
				              <p>Status: released</p>
				              <div class="progress"><div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div></div>
				              <ul>
				              	<li>Language: C++11/GLSL</li>
				              	<li>Licence: GPLv3</li>
				              	<li>Sources: <a href="http://sourceforge.net/projects/gridrpcdm" target="_blank" class="text-%class%">http://sourceforge.net/projects/gridrpcdm</a></li>
				              </ul>',
			),
			array(
				'title'   => 'MDMA',
				'content' => '<p>MDMA (Motion Detection Midi Adaptor) is a augmented reality program providing gesture based control to MIDI devices.</p>
				              <p>Status: released</p>
				              <div class="progress"><div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div></div>
				              <ul>
				              	<li>Language: C++11</li>
				              	<li>Licence: CeCILL-B</li>
				              	<li>Website: <a href="https://graal.ens-lyon.fr/mdma/en" target="_blank" class="text-%class%">http://graal.ens-lyon.fr/mdma/en</a></li>
				              	<li>Sources: <a href="https://github.com/Amxx/MDMA" target="_blank" class="text-%class%">https://github.com/Amxx/MDMA</a></li>
				              </ul>',
			),
			array(
				'title'   => 'Geo3D',
				'content' => '<p>Geo3D provides terrain reconstruction from samples of point using a delaunay reconstruction.</p>
				              <p>Status: discontinued</p>
				              <div class="progress"><div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div></div>
				              <ul>
				              	<li>Language: C++ or C++11</li>
				              	<li>Licence: GPLv3</li>
				              	<li>Sources: <a href="https://github.com/Amxx/Geo3D" target="_blank" class="text-%class%">https://github.com/Amxx/Geo3D</a></li>
				              </ul>',
			),
			array(
				'title'   => 'Lenaction',
				'content' => '<p>Lenaction is a basic image processing library coupled with a custom interpretor for scripted pipelining.</p>
				              <p>Status: discontinued</p>
				              <div class="progress"><div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div></div>
				              <ul>
				              	<li>Language: C++11</li>
				              	<li>Licence: GPLv3</li>
				              	<li>Sources: <a href="https://github.com/Amxx/Lenactions" target="_blank" class="text-%class%">https://github.com/Amxx/Lenactions</a></li>
				              </ul>',
			),
			array(
				'title'   => 'QtTwitGraph',
				'content' => '<p>QtTwitGraph is a real time big data aquisition and analysis tools for studying communities on twitter.</p>
				              <p>Status: discontinued</p>
				              <div class="progress"><div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div></div>
				              <ul>
				              	<li>Language: C++/Qt
				              	<li>Licence: GPLv3
				              	<li>Sources: <a href="//shared.hadriencroubois.com/work/2012/QtTWitGraph_v2.tar.gz" target="_blank" class="text-%class%">QtTwitGraph_v2.tar.gz</a>
				              </ul>',
			),
		),
	);

?>