<?php
	$sections['teaching'] = array(
		'title'            => 'Teaching',
		'type'             => 'blocks',
		'settings'         => array('class' => 'info', 'width' => 'col-md-6'),
		'headerBackground' => 'assets/img/05-teaching.jpg',
		'icon'             => 'school',
		'content'          => array(
			array(
				'title'    => '[2016-2017] Digital Image',
				'content'  => '<h5>M1IF - ENS de Lyon - 2016-2017</h5>
<h3>Teaching materials:</h3>
<ul>
	<li>
		[17 feb] TP1 - Image manipulation
		<ul>
			<li>Assignment (fr): <a href="//shared.hadriencroubois.com/teaching/2016-M1-DG/tp1.fr.pdf" target="_blank" class="text-%class%">tp1.fr.pdf</a> (152.8 ko)</li>
			<li>Assignment (en): <a href="//shared.hadriencroubois.com/teaching/2016-M1-DG/tp1.en.pdf" target="_blank" class="text-%class%">tp1.en.pdf</a> (159.7 ko)</li>
			<li>Archive:         <a href="//shared.hadriencroubois.com/teaching/2016-M1-DG/tp1.tar.gz" target="_blank" class="text-%class%">tp1.tar.gz</a> (11.6 ko)</li>
		</ul>
	</li>
	<li>
		[17 feb] TP2 - Histogram manipulation
		<ul>
			<li>Assignment (en): <a href="//shared.hadriencroubois.com/teaching/2016-M1-DG/tp2.en.pdf" target="_blank" class="text-%class%">tp2.en.pdf</a> (208.0 ko)</li>
			<li>Archive:         <a href="//shared.hadriencroubois.com/teaching/2016-M1-DG/tp2.tar.gz" target="_blank" class="text-%class%">tp2.tar.gz</a> (38.2 ko)</li>
		</ul>
	</li>
	<li>
		[9 march] TP3 - Local filtering, gradient and Corner detection
		<ul>
			<li>Assignment (en): <a href="//shared.hadriencroubois.com/teaching/2016-M1-DG/tp3.en.pdf" target="_blank" class="text-%class%">tp3.en.pdf</a> (284.7 ko)</li>
		</ul>
	</li>
</ul>
',
				'archived' => false,
			),
			array(
				'title'    => '[2016-2017] Distributed systems',
				'content'  => '<h5>M1IF - ENS de Lyon - 2016-2017</h5>
<h3>Teaching materials:</h3>
<ul>
	<li>
		[14 & 21 feb] TP1 - Erlang for distributed systems
		<ul>
			<li>Assignment: <a href="//shared.hadriencroubois.com/teaching/2015-M1-SystDist/tp1.pdf" target="_blank" class="text-%class%">tp1.pdf</a> (161.7 ko)</li>
			<!-- <li>Correction: <a href="//shared.hadriencroubois.com/teaching/2015-M1-SystDist/tp1_correction.erl" target="_blank" class="text-%class%">tp1_correction.erl</a> (3.4 ko)</li> -->
		</ul>
	</li>
	<li>
		[7 march] TP2 - Token passing
		<ul>
			<li>Assignment: <a href="//shared.hadriencroubois.com/teaching/2015-M1-SystDist/tp2.pdf" target="_blank" class="text-%class%">tp2.pdf</a> (156.5 ko)</li>
			<li>Correction: <a href="//shared.hadriencroubois.com/teaching/2015-M1-SystDist/tp2_correction.erl" target="_blank" class="text-%class%">tp2_correction.erl</a> (2.6 ko)</li>
		</ul>
	</li>
</ul>
',
				'archived' => false,
			),
			array(
				'title'    => '[2015-2016] Distributed systems',
				'content'  => '<h5>M1IF - ENS de Lyon - 2015-2016</h5>
<h3>Teaching materials:</h3>
<ul>
	<li>
		[4 feb] TP1 - Erlang for distributed systems
		<ul>
			<li>Assignment: <a href="//shared.hadriencroubois.com/teaching/2015-M1-SystDist/tp1.pdf" target="_blank" class="text-%class%">tp1.pdf</a> (161.7 ko)</li>
			<li>Correction: <a href="//shared.hadriencroubois.com/teaching/2015-M1-SystDist/tp1_correction.erl" target="_blank" class="text-%class%">tp1_correction.erl</a> (3.4 ko)</li>
		</ul>
	</li>
	<li>
		[11 feb] TP2 - Token passing
		<ul>
			<li>Assignment: <a href="//shared.hadriencroubois.com/teaching/2015-M1-SystDist/tp2.pdf" target="_blank" class="text-%class%">tp2.pdf</a> (156.5 ko)</li>
			<li>Correction: <a href="//shared.hadriencroubois.com/teaching/2015-M1-SystDist/tp2_correction.erl" target="_blank" class="text-%class%">tp2_correction.erl</a> (2.6 ko)</li>
		</ul>
	</li>
	<li>
		[18 feb] TP3 - Sliding window
		<ul>
			<li>Assignment: <a href="//shared.hadriencroubois.com/teaching/2015-M1-SystDist/tp3.pdf" target="_blank" class="text-%class%">tp3.pdf</a> (187.8 ko)</li>
			<li>Skeleton: <a href="//shared.hadriencroubois.com/teaching/2015-M1-SystDist/tp3_skeleton.erl" target="_blank" class="text-%class%">tp3_skeleton.erl</a> (637 ko)</li>
			<li>Correction: <a href="//shared.hadriencroubois.com/teaching/2015-M1-SystDist/tp3_correction.erl" target="_blank" class="text-%class%">tp3_correction.erl</a> (2.3 ko)</li>
		</ul>
	</li>
	<li>
		[3 march] [Optional] TP4 - Grid deployment
		<ul>
			<li>Assignment: <a href="//shared.hadriencroubois.com/teaching/2015-M1-SystDist/tp4.pdf" target="_blank" class="text-%class%">tp4.pdf</a> (147.0 ko)</li>
		</ul>
	</li>
	<li>
		[10 march] Project presentation
		<ul>
			<li>Assignment: <a href="//shared.hadriencroubois.com/teaching/2015-M1-SystDist/project.pdf" target="_blank" class="text-%class%">project.pdf</a> (242.5 ko)</li>
		</ul>
	</li>
</ul>
',
				'archived' => true,
			),
			array(
				'title'    => '[2015-2016] Parallel and Distributed Algorithms and Programs',
				'content'  => '<h5>M1IF - ENS de Lyon - 2015-2016</h5>

<h3>Teaching materials:</h3>
<ul>
	<li>
		[18 sept] TP1 - Introduction to MPI
		<ul>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/tp1-introduction/MPI-Presentation.pdf" target="_blank" class="text-%class%">Slides</a> (355.2 ko)</li>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/tp1-introduction/pi.c" target="_blank" class="text-%class%">pi.c</a> (1.5 ko)</li>
		</ul>
	</li>
	<li>
		[25 sept & 2 oct] TP2 - Sorting networks
		<ul>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/tp2-sorting/tp2.pdf" target="_blank" class="text-%class%">tp2.pdf</a> (182.6 ko)</li>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/tp2-sorting/skeleton.c" target="_blank" class="text-%class%">skeleton.c</a> (1.7 ko)</li>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/tp2-sorting/tp2-correction.tar.gz" target="_blank" class="text-%class%">tp2-correction.tar.gz</a> (2.0 ko)</li>
		</ul>
	</li>
	<li>
		[9 oct] TP3 - Matrix multiplication
		<ul>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/tp3-collective/tp3.pdf" target="_blank" class="text-%class%">tp3.pdf</a> (282.7 ko)</li>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/tp3-collective/squeleton.c" target="_blank" class="text-%class%">skeleton.c</a> (3.1 ko)</li>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/tp3-collective/tp3-correction.tar.gz" target="_blank" class="text-%class%">tp3-correction.tar.gz</a> (2.2 ko)</li>
		</ul>
	</li>
	<li>
		[16 oct] TD1 - P-RAM
		<ul>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/td1.pdf" target="_blank" class="text-%class%">td1.pdf</a> (264.3 ko)</li>
		</ul>
	</li>
	<li>
		[23 oct] TD2 - P-RAM & Linear networks of processors
		<ul>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/td2.pdf" target="_blank" class="text-%class%">td2.pdf</a> (258.3 ko)</li>
		</ul>
	</li>
	<li>
		[6 nov] TP4 - Pipelined matrix multiplication : Cannon"s algorithm
		<ul>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/tp4-pipeline/tp4.pdf" target="_blank" class="text-%class%">tp4.pdf</a> (200.3 ko)</li>
		</ul>
	</li>
	<li>
		[13 nov] TP5 - Simulation & benchmarking using Simgrid
		<ul>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/tp5-simgrid/tp5.pdf" target="_blank" class="text-%class%">tp5.pdf</a> (148.9 ko)</li>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/tp5-simgrid/tp5-simgrid.tar.gz" target="_blank" class="text-%class%">archive</a> (11.0 ko)</li>
		</ul>
	</li>
	<li>
		[20 nov] TP6 - Simulation & benchmarking using Simgrid (2)
		<ul>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/tp6-simgrid2/tp6.pdf" target="_blank" class="text-%class%">tp6.pdf</a> (146.2 ko)</li>
		</ul>
	</li>
	<li>
		[27 nov] TD3 - Scheduling (1)
		<ul>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/td3.pdf" target="_blank" class="text-%class%">td3.pdf</a> (282.0 ko)</li>
		</ul>
	</li>
	<li>
		[2 dev] TD4 - Scheduling (2)
		<ul>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/td4.pdf" target="_blank" class="text-%class%">td4.pdf</a> (230.2 ko)</li>
		</ul>
	</li>
	<li>
		[4 dec] TD5 - Automatic parallelization
		<ul>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/td5.pdf" target="_blank" class="text-%class%">td5.pdf</a> (231.9 ko)</li>
		</ul>
	</li>
	<li>
		[18 dec] TD6 - Automatic parallelization (2)
		<ul>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/td6.pdf" target="_blank" class="text-%class%">td6.pdf</a> (147.0 ko)</li>
		</ul>
	</li>
	<li>
		[11 jan] TD7 - Scheduling (3)
			<ul>
			<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/td7.pdf" target="_blank" class="text-%class%">td7.pdf</a> (179.9 ko)</li>
		</ul>
	</li>
</ul>
<h3>Extra ressources:</h3>
<ul>
	<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/project/project.pdf" target="_blank" class="text-%class%">Project assignement</a> (324.7 ko)</li>
	<li><a href="//shared.hadriencroubois.com/teaching/2015-M1-AlgoPar/project/tools.tar.gz" target="_blank" class="text-%class%">Tool box</a> (167.7 ko)</li>
	<li>I expect every student to read <a href="//shared.hadriencroubois.com/teaching/ressources/goldberg.pdf" target="_blank" class="text-%class%">“What Every Computer Scientist Should Know About Floating-Point Arithmetic”</a> (also available as an html page <a href="http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html" target="_blank" class="text-%class%">here</a>)</li>
</ul>',
				'archived' => true,
			),
			array(
				'title'    => '[2015-2016] Architecture système et reseau (ASR1)',
				'content'  => '<h5>L3IF - ENS de Lyon - 2015-2016</h5><ul><li><a href="http://logos.cs.uic.edu/366/notes/mips%20quick%20tutorial.htm" target="_blank" class="text-%class%">MIPS Quick Reference Guide</a></li></ul>',
				'archived' => true,
			),
			array(
				'title'    => '[2013-2014] Acquisition et analyse d\'images',
				'content'  => '<h5>M2 IGI - UCBL - 2013-2014</h5><ul><li><a href="//shared.hadriencroubois.com/teaching/2013-M2-IGI/squelettisation.pdf" target="_blank" class="text-%class%">La squelettisation</a> (1.2 mo)</li></ul>',
				'archived' => true,
			),
			array(
				'title'    => '[2013-2014] Pascal tutorial classes for “classes prepa”',
				'content'  => '<h5>Prepa HEC - 2013-2014</h5>
<ul>
<li><a href="//shared.hadriencroubois.com/teaching/2013-ECS-pascal/fiche.pdf" target="_blank" class="text-%class%">Aide mémoire Pascal</a> (132.3 ko)</li>
<li><a href="//shared.hadriencroubois.com/teaching/2013-ECS-pascal/tp1.pdf" target="_blank" class="text-%class%">TP1</a> (152.7 ko)</li>
<li><a href="//shared.hadriencroubois.com/teaching/2013-ECS-pascal/tp2.pdf" target="_blank" class="text-%class%">TP2</a> (106.4 ko)</li>
<li><a href="//shared.hadriencroubois.com/teaching/2013-ECS-pascal/tp3.pdf" target="_blank" class="text-%class%">TP3</a> (158.4 ko)</li>
<li><a href="//shared.hadriencroubois.com/teaching/2013-ECS-pascal/tp4.pdf" target="_blank" class="text-%class%">TP4</a> (198.4 ko)</li>
<li><a href="//shared.hadriencroubois.com/teaching/2013-ECS-pascal/corrige1.pdf" target="_blank" class="text-%class%">Correction de devoirs n°1</a> (227.4 ko)</li>
<li><a href="//shared.hadriencroubois.com/teaching/2013-ECS-pascal/tp6.pdf" target="_blank" class="text-%class%">TP6</a> (127.0 ko)</li>
</ul>
<div style="text-align: center;">
Tous les codes sources sont disponible sur GitHub :<br/>
<a href="https://github.com/Amxx/PrepaPascal" target="_blank" class="text-%class%">https://github.com/Amxx/PrepaPascal</a>
</div>',
				'archived' => true,
			),
			array(
				'title'    => '[2012-2013] Caml tutorial classes for “classes prepa”',
				'content'  => '<h5>Prepa MP/MP* - 2012-2013</h5>

<p>TP 1 - Remise à niveau (2 & 9 oct)</p>
<ul>
<li><a href="//shared.hadriencroubois.com/teaching/2012-MP-caml/td01.pdf" target="_blank" class="text-%class%">sujet</a> (107.3 ko)</li>
<li><a href="//shared.hadriencroubois.com/teaching/2012-MP-caml/corrige_td01.ml" target="_blank" class="text-%class%">corrigé</a> (8.6 ko)</li>
</ul>
<p>TP 2 - Les automates (23 & 30 oct, 20 & 27 nov)</p>
<ul>
<li><a href="//shared.hadriencroubois.com/teaching/2012-MP-caml/td02.pdf" target="_blank" class="text-%class%">sujet</a> (178,0 ko)</li>
<li><a href="//shared.hadriencroubois.com/teaching/2012-MP-caml/corrige_td02.ml" target="_blank" class="text-%class%">corrigé</a> (3.5 ko)</li>
</ul>
<p>TP 3 - Le codage de Huffman (4 & 18 nov)</p>
<ul>
<li><a href="//shared.hadriencroubois.com/teaching/2012-MP-caml/td03.pdf" target="_blank" class="text-%class%">sujet</a> (185,7 ko)</li>
<li><a href="//shared.hadriencroubois.com/teaching/2012-MP-caml/corrige_td03.ml" target="_blank" class="text-%class%">corrigé</a> (2.0 ko)</li>
</ul>
<p>TP 4 - Les Arbres rouges-noirs (5 fev)</p>
<ul>
<li><a href="//shared.hadriencroubois.com/teaching/2012-MP-caml/td04.pdf" target="_blank" class="text-%class%">sujet</a> (139,8 ko)</li>
<li><a href="//shared.hadriencroubois.com/teaching/2012-MP-caml/corrige_td04.ml" target="_blank" class="text-%class%">corrigé</a> (1.5 ko)</li>
</ul>
<p>TP 5 - Multiplications rapide (12 fev)</p>
<ul>
<li><a href="//shared.hadriencroubois.com/teaching/2012-MP-caml/td05.pdf" target="_blank" class="text-%class%">sujet</a> (165,9 ko)</li>
<li><a href="//shared.hadriencroubois.com/teaching/2012-MP-caml/corrige_td05.ml" target="_blank" class="text-%class%">corrigé</a> (2.5 ko)</li>
</ul>
<p>TP 6 - La programmation dynamique (5 mars)</p>
<ul>
<li><a href="//shared.hadriencroubois.com/teaching/2012-MP-caml/td06.pdf" target="_blank" class="text-%class%">sujet</a> (170,5 ko)</li>
<li><a href="//shared.hadriencroubois.com/teaching/2012-MP-caml/corrige_td06.ml" target="_blank" class="text-%class%">corrigé</a> (2.7 ko)</li>
</ul>
<p>TP 7 - Les Graphs (12 & 19 mars)</p>
<ul>
<li><a href="//shared.hadriencroubois.com/teaching/2012-MP-caml/td07.pdf" target="_blank" class="text-%class%">sujet</a> (159,2 ko)</li>
<li>corrigé bientot disponible</li>
</ul>',
				'archived' => true,
			),
		),
	);
?>
